#! /bin/sh
# Credits: https://github.com/ericmurphyxyz/archrice/blob/master/.local/bin/startup

internal_monitor=eDP1
external_monitor=HDMI2

monitor_add() {
	desktops=5  # How many desktops to move to the second monitor

	for desktop in $(bspc query -D -m $internal_monitor | sed "$desktops"q)
  do
		# TODO: put a condition here to not move anything if the monitor already has 5 desktops
		bspc desktop $desktop --to-monitor $external_monitor
  done

  # Remove "Desktop" created by bspwm
  bspc desktop Desktop --remove
}

monitor_remove() {
	bspc monitor $internal_monitor -a Desktop  # Temp desktop because one desktop required per monitor

	# Move everything to external monitor to reorder desktops
	for desktop in $(bspc query -D -m $internal_monitor)
	do
		bspc desktop $desktop --to-monitor $external_monitor
	done

	# Now move everything back to internal monitor
	bspc monitor $external_monitor -a Desktop  # Temp desktop

	for desktop in $(bspc query -D -m $external_monitor)
	do
		bspc desktop $desktop --to-monitor $internal_monitor
	done

	bspc desktop Desktop --remove  # Remove temp desktops
}

if [[ $(xrandr -q | grep "$external_monitor connected") ]]; then
    monitor_add
else
    monitor_remove
fi

# Wallpaper
nitrogen --restore &
# Bar
$HOME/.config/polybar/launch.sh
