#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

	xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

	xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# desktop
picom &                                                             # start compositor
xfce4-power-manager &                                               # power manager
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &         # control system-wide privileges
eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) # credential manager
thunar -daemon &                                                    # file manager
nm-applet --indicator &                                             # wifi
blueman-applet &                                                    # bluetooth tray icon
xrandr --output HDMI-1-0 --mode 1920x1080 --rate 60 --right-of eDP1 # set refresh rate correctly

# user programs
vorta --daemonize
protonmail-bridge --noninteractive &

# window manager
/usr/bin/prime-offload     # prime-offload (nvidia gpu)
awesome                    # --- start window manager ---
sudo /usr/bin/prime-switch # execute after logout (necessary for optimus manager - nvidia gpu)
