#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

	xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

	xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

picom &                                                             # start compositor
nm-applet --indicator &                                             # wifi
pnmixer &                                                           # audiocontrol applet in systray
blueman-applet &                                                    # bluetooth tray icon
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &         # control system-wide privileges
eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) # credential manager
xfce4-power-manager &                                               # power manager
/usr/bin/prime-offload                                              # prime-offload (nvidia gpu)
awesome                                                             # --- start window manager ---
sudo /usr/bin/prime-switch                                          # execute after logout (necessary for optimus manager - nvidia gpu)
