# profile file. Runs on login. Environmental variables are set here.
#
# Default programs:
export EDITOR="$HOME/bin/nvim.appimage"
export TERMINAL="kitty"
export BROWSER="firefox"

# Set env variables
export WH="/mnt/c/Users/dsilva"
export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcloud_keys.json"

# XDG:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# Clean up:
export XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority" # This line will break some DMs.
export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc"
export AWS_CONFIG_FILE="${XDG_CONFIG_HOME}/aws/config"
export DOCKER_CONFIG="${XDG_CONFIG_HOME}/docker"
export GNUPGHOME="${XDG_DATA_HOME}/gnupg"
export LESSHISTFILE="${XDG_CACHE_HOME}/less/history"
export npm_config_cache="${XDG_CACHE_HOME}/npm"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME}/pass"
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export CUDA_CACHE_PATH="${XDG_CACHE_HOME}/nv"
export LESSKEY="${XDG_CONFIG_HOME}/less/lesskey"
export NODE_REPL_HISTORY="${XDG_CACHE_HOME}/node_repl_history"
export AWS_SHARED_CREDENTIALS_FILE="${XDG_CONFIG_HOME}/aws/credentials"
export HISTFILE="${XDG_DATA_HOME}/history"
export __GL_SHADER_DISK_CACHE_PATH="${XDG_CACHE_HOME}/nv"
export PARALLEL_HOME="${XDG_CONFIG_HOME}/parallel"
export PYLINTHOME="${XDG_CACHE_HOME}/pylint"
export CONDARC="${XDG_CONFIG_HOME}/conda/condarc"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="${XDG_CONFIG_HOME}/java"
export ICEAUTHORITY="${XDG_CACHE_HOME}/ICEauthority"
export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME}/jupyter"
export SQLITE_HISTORY="${XDG_DATA_HOME}/sqlite_history"
export TEXMFHOME="${XDG_DATA_HOME}/texmf"
export TEXMFVAR="${XDG_CACHE_HOME}/texlive/texmf-var"
export TEXMFCONFIG="${XDG_CONFIG_HOME}/texlive/texmf-config"
export WINEPREFIX="${XDG_DATA_HOME}/wineprefixes/default"
export GOPATH="${XDG_DATA_HOME}/go"

# Set qt theme with kvantum:
export QT_STYLE_OVERRIDE=kvantum

# Startx silent:
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx -- vt1 &> /dev/null
fi
