# Enable Powerlevel10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set Zsh Theme
ZSH_THEME="powerlevel10k/powerlevel10k"
DEFAULT_USER="dsilva"

# Set plugins
plugins=(
  docker
  docker-compose
  vi-mode
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# ------------------- User configuration -------------------
# Vi-mode settings
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true
VI_MODE_SET_CURSOR=true
bindkey -v

# Configure autosuggestions bindkeys
bindkey '^f' autosuggest-accept  # ctrl + f
bindkey '^x' autosuggest-clear  # ctrl + x

# Activate nord dircolors
test -r "~/.dir_colors" && eval $(dircolors ~/.dir_colors)

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Aliases
alias watch-nvidia="watch -n 1 nvidia-smi"
alias tlmgr='/usr/share/texmf-dist/scripts/texlive/tlmgr.pl --usermode'

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/dotfiles/bin" ] ; then
    PATH="$HOME/dotfiles/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Set env variables
export VISUAL="/usr/bin/nvim"
export EDITOR="/usr/bin/nvim"
export TERM="xterm-256color"

# ------------------- External configurations -------------------
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/miniconda3/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
