# ------------------- Zsh configuration -------------------
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

DEFAULT_USER="dsilva"

# Set plugins
plugins=(
  aws
  docker
  docker-compose
  vi-mode
  zsh-autosuggestions
  zsh-syntax-highlighting
  gcloud
)

# Set prompt theme
fpath+=$ZSH/custom/plugins/pure
autoload -U promptinit; promptinit
prompt pure

source $ZSH/oh-my-zsh.sh

# Vi-mode settings
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true
VI_MODE_SET_CURSOR=true
bindkey -v

# Configure autosuggestions bindkeys
bindkey '^f' autosuggest-accept  # ctrl + f
bindkey '^x' autosuggest-clear  # ctrl + x

# ------------------- User configuration -------------------
# Activate nord dircolors
test -r "~/.dir_colors" && eval $(dircolors ~/.dir_colors)

# Aliases
alias watch-nvidia="watch -n 1 nvidia-smi"
alias tlmgr='/usr/share/texmf-dist/scripts/texlive/tlmgr.pl --usermode'
alias vim='nvim.appimage'
alias xpl='explorer.exe'

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes dotfiles bin if it exists
if [ -d "$HOME/dotfiles/bin" ] ; then
    PATH="$HOME/dotfiles/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Set env variables
export VISUAL="$HOME/bin/nvim.appimage"
export EDITOR="$HOME/bin/nvim.appimage"
export TERM="xterm-256color"
export WH="/mnt/c/Users/dsilva"
export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcloud_keys.json"

# ------------------- External configurations -------------------
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/miniconda3/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
